name: Cloud-roll-C

on:
  schedule:
    # 15:00 MSK = 12:00 UTC
    - cron: '0 12 * * *'
  workflow_dispatch:

jobs:
  roll:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: install dependencies
        run: pip install -r requirements.txt

      - name: write AES key
        env:
          AES_KEY: ${{ secrets.AES_KEY }}
        run: echo -n "$AES_KEY" > aes_key.txt

      - name: run roll-C
        run: |
          cd $GITHUB_WORKSPACE
          PYTHONPATH=src python3 -m blindentropyfork.roll --group C --key $(cat aes_key.txt)

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "C-roll + OTS $(date -u +'%Y-%m-%d %H:%M')"
          file_pattern: logs/log_template.csv logs/log_template.csv.ots
          branch: master
