name: Cloud‑roll‑C

on:
  schedule:
    # 15:00 MSK = 12:00 UTC
    - cron: '0 12 * * *'
  workflow_dispatch:

jobs:
  roll:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - run: pip install requests pycryptodome

      - name: write‑key
        run: echo "$AES_KEY" > aes_key.txt
        env:
          AES_KEY: ${{ secrets.AES_KEY }}

      - name: roll‑C
        run: python blind_entropy_roll.py --group C --key $(cat aes_key.txt)

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "C‑roll $(date -u +'%Y-%m-%d %H:%M')"
          file_pattern: log_template.csv
          branch: main
